language: csharp
mono: none
dotnet: 3.0.100
before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
  - nvm install node
  - nvm use node
  - which node
  - which npm
script:
  - sudo bash ./scripts/build/create-folders.sh
  - sudo bash ./scripts/build/build-ui.sh
  - sudo bash ./scripts/build/build-server.sh
deploy:
  provider: releases
  api_key:
    secure: "q6h/Bdd+NuRD8OhnrqCjbzYgCVo5YNdVNYIw6/l88FV54SoCF9xrfOxzU/L5lpJhJqzvrRr5dBMcatphVkIaaJBC3QNdOVIn7dCy++SRzTaahVIwbdbLbLObizrsDmi8jsIU7u2jPZ2/AAxX5RdhqfmnGy/XEMUPXPXrFv5M6nYEgD7FR68aFTSPvMYj2yyxi4Job6l9HeC+pa9KH1xHB1+xnZ8Rr6EIrG5nrbge4341i7xdH3BebAgoN5V/EcJWPnkEJ+J7odDUjUj/CjBnwTHMi6spbcE8M6BX4DotxeGNEBtdX2UvhCNvVoDHGjaQ7fspWGYrDIuYpl4rwL3IgMj+WuONb6f0yx0TkKTiaN0VTodYIAtyWigLC6RKWo6XRCvl+qywCfG2HNym3Q0hPsLMEQdX3pvdvtyzjfRK2ohGPi7QEOwzoqXF+jV+ZJzaqWa1u9NHkj3BReLJTrrKdDiZv5RSSAT3pGPETYob+QLCBbH7qrfMPEdCdpq+tTSDPNQYLHrNBw9gS5z2ym+BYAlwnge9AREzAfr5As+fnrMdzMFMDNHHWTbYjSonZSa2jRmIvXvoIFpaAmKo5Ls6Xeqtp/8j0FK3Yu3GV15etm3FoFBStrjrmzPrVa9OsikKkPO9vw7AiR3okQ1c73Iv8ddCiMAa+2A+QSgDfr6AfnQ="
  file_glob: true
  file: ./dist/*