language: csharp
mono: none
dotnet: 3.0.100
before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install node
  - nvm use node
script:
  - sudo bash ./scripts/build/create-folders.sh
  - sudo bash ./scripts/build/build-ui.sh
  - sudo bash ./scripts/build/build-server.sh