language: csharp
mono: none
dotnet: 3.0.100
before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
  - nvm install node
  - nvm use node
  - which node
  - which npm
script:
  - sudo bash ./scripts/build/create-folders.sh
  - sudo bash ./scripts/build/build-ui.sh
  - sudo bash ./scripts/build/build-server.sh
deploy:
  provider: releases
  api_key:
    secure: "SWupQr1aAgvxYK99xmPvAxIE2dloI1TvjRVe7RflGKoS8kKJYtEFhpbJK3AW5DRLZ/p8sxtvzJHU+P8xaoYt81UdFwoCakOxLeAx8o0GjaQySFTjpatYzFru8idbmButDDwB2xG1/A2T2/efYEY+fSY5wMPo2dj4/keJZ3s8t6pRGepBT4UJKc1z60dFIAyE/svkA9ZXpjicGkBLm2l+tFpLyO4KJIvsI5QWcfgBMz7B2fij++0wRMhW6ppa9O9smoIfzYTObtqkt3WaU7wg/Ge51+c6kD8YwtwHs1UsUYUdzfKnRnEqmioOwBgqQwbfvpbdgGUbnPeyjK8Yqk3F2a6kTjPxai+VGdhMBc1iYeFTCvhtP74R9gd2GFG6TcNj+7uCWkUhdCp2jCY6bXg6e3//ETeEWPX1p7yA05xo8NmSfVO1KU76rDudkOOlFY7Caz5keTskrQR81DG7VIzBVlfbOMmLrT4ObA26Hfv+BHqNSoECtAxCbcNzAzVfHPA5vGfdmvfIuX60dZEzk9mNOAbRvaIOFRpj/NWO2nmAQlwvLTV+7cw5kxKncfQkkVKhqF5di2OZ36yjm0RuPybp5ewQ0YoMWblSJIzhjgXaNrMC2Zgo4s5+ytHl3DbqACP8g1t5Le7g57m2iix+fDmo8dz68vCN8G7vNLrLlcd6E0Q="
  file_glob: true
  file: ./dist/*