language: csharp
mono: none
dotnet: 3.0.100
before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install node
  - nvm use node
script:
  - sudo bash ./scripts/build/build-server.sh
  - sudo bash ./scripts/build/build-ui.sh